### ISSUE TITLE
Issues when multiple players are on the server

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-RPGDrops#1]
> The plugin works perfectly when there's only one person on the server. However, when multiple individuals join, items do not stack, and large items disappear and reappear after some time. Sometimes, when they are on the ground, they cannot be picked up.

**Comment by VacAge** [comment]
Good afternoon! 

I found errors in multiplayer, they clearly show that when 1 or more players enter, when 1 item lies on the floor, it may disappear and not be displayed **for all or one player**. Also, if you turn off the option `pickup_on_interact: false` in the settings, which is very useful, then the item if it disappears it is impossible to lift. But they always appear if there are 2 or more of them
It is also important to note that when the player is 1, the plugin works perfectly

[YouTube Video](https://youtu.be/oeNHU9fZnZw)
 Current: git-Purpur-2134 (MC: 1.20.4)*

**Comment by LoneDev6** [comment]
Thanks so much, I'll try to reproduce the issue and fix it as soon as possible

**Comment by VacAge** [comment]
Is there any news?

**Comment by BiigToastie** [comment]
im running into the same issue on 1.20.4 Paper
Items are sometimes still displayed for others, even though they have already been picked up and only go away after a reconnect.
Conversely, sometimes the elements are not visible and/or cannot be removed.
and then only visible after reconnection

**Comment by BiigToastie** [comment]
pleeease fix this fast, because players are really confused what happening ^^
